server:
  port:8080
  servlet:
    context-path: /api

spring:
  application:
    name: traficast-backend

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/traficast
    username: traficast
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss

# 외부 API 설정
model-api:
  url: http://localhost:8000
  timeout: 30000

# 스케줄링 설정
scheduling:
  enabled: true
  prediction:
    cron: "0 0 0 * * ?" # 매일 자정

# 파일 업로드 설정
file:
  upload:
    max-size: 10MB
    allowed-types: text/csv, application/csv

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

  endpoints:
    health:
      show-details: always

logging:
  level:
    com.traficast: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
