spring:
  jpa:
    show-sql: true

  devtools:
    restart:
      enabled: true

logging:
  level:
    root: INFO
    com.traficast: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG